### PR TITLE
Add OSX arm64 build

### PR DESCRIPTION
**Pull request by timj**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by ccordoba12** [comment]
I think this package can be made `noarch`. I'm not totally sure though because it depends on `humanfriendly`, which is a regular package.

@ocefpaf, what do you say?

**Comment by erykoff** [comment]
I think it's just fine for noarch packages to depend on non-noarch packages.  I also agree this could be made noarch, but at the very least we wanted to be able to use it on osx-arm64.

**Comment by ccordoba12** [comment]
Sure, but if we can make it `noarch` now, it'd be better for maintenance.

**Comment by erykoff** [comment]
I've tried this via the bot on #36 but it needs a maintainer to edit the `python` host and run lines (or at least I can't figure out how).

**Comment by timj** [comment]
Closed by #37

**Pull request closed without merging**
